config/routes.rb
Rails.application.routes.draw do
  get 'cookies/set'
  get 'cookies/show'
  get 'cookies/delete'

  get 'home/index'

  resources :sessions, only: %i[new create destroy]
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true, uniqueness: { case_sensitive: false }

    # include BCrypt
    # validate :password_present?

    # def password=(new_password)
    #     @password = Password.create(new_password)
    #     self.password_digest = @password
    # end

    # def password
    #     return nil unless password_digest.present?

    #     @password ||= Password.new(password_digest)
    # end

    # def authenticate(unencrypted_password)
    #     self.password.is_password?(unencrypted_password) && self
    # end

    # def password_present?
    #     errors.add(:password, :blank) unless password.present?
    # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    helper_method :current_user

    protected
    def current_user
        @current_user = User.find(session[:user_id]) if session[:user_id]
    end
end

app/controllers/cookies_controller.rb
class CookiesController < ApplicationController
  def set
    session[:current_user] = {
      '10': {
        name: 'CookieJammer',
        client_id: '784325gqwhwq343242'
      }
    }

    cookies[:session_id] = '10'
    redirect_to cookies_show_path
  end

  def show
    return unless cookies[:session_id]

    current_user = session[:current_user][cookies[:session_id]]
    @user_alias = current_user[:name.to_s]
    @client_id = current_user[:client_id.to_s]
  end

  def delete
    cookies.delete :session_id

    redirect_to cookies_show_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logueado Correctamente'
    else
      flash.now[:notice] = 'Email o password inválida'
      render action :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Signed out successfully'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cookies_helper.rb
module CookiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/cookies/delete.html.erb
<h1>Cookies#delete</h1>
<p>Find me in app/views/cookies/delete.html.erb</p>

app/views/cookies/set.html.erb
<h1>Cookies#set</h1>
<p>Find me in app/views/cookies/set.html.erb</p>

app/views/cookies/show.html.erb
<h1>Cookies#show</h1>

<table>
    <tr>
        <td><strong>User Alias:</strong> </td>
        <td><%= @user_alias %></td>
    </tr>
    <tr>
        <td><strong>Client Id:</strong> </td>
        <td><%= @client_id %></td>
    </tr>
</table>

app/views/home/index.html.erb
<h1><%= current_user ? "Hola user: #{current_user.email}!" : 'Hola extraño' %></h1>

<% if current_user %>
    <%= link_to 'Log Out', session_path(current_user), method: :delete %>
<% else %>
    <%= link_to 'Sign In', new_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthenticationProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>